language: ruby
rvm:
  - "1.9.3"
services:
  - mongodb
  - elasticsearch
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.11.deb && sudo dpkg -i elasticsearch-0.90.11.deb && sudo service elasticsearch restart
script: bundle exec rspec
