# This is only currently used by Travis for testing
version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: "es.edx"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
  mongo:
    image: mongo:3.2.21
    container_name: "mongo.edx"
  forum-base:
    image: edxops/forum:ruby257 # TODO: switch back to latest after configuration release
    container_name: forum_testing
    volumes:
      - ..:/edx/app/forum/cs_comments_service
    environment:
      MONGOID_AUTH_MECH: ""
  forum:
    extends: forum-base
    command: tail -f /dev/null
    depends_on:
      - "elasticsearch"
      - "mongo"
  test-forum:
    extends: forum-base
    command: /edx/app/forum/cs_comments_service/.travis/run_tests.sh
    depends_on:
      - "elasticsearch"
      - "mongo"

volumes:
  data01:
    driver: local
